name: Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant Gradle permission
        run: chmod +x gradlew

      # Clone and publish guiAPI into ~/.m2
      - name: Publish guiAPI to mavenLocal
        run: |
          git clone --depth 1 https://github.com/ToolkitMC/guiAPI.git /tmp/guiAPI

          cd /tmp/guiAPI

          chmod +x gradlew

          ./gradlew \
            clean \
            publishToMavenLocal \
            --stacktrace \
            --info \
            --no-daemon

      # Debug generated Maven artifacts
      - name: Debug local Maven
        run: |
          echo "=== FULL .m2 CONTENT ==="
          find ~/.m2 -type f || true

      # Build current project
      - name: Build
        run: |
          ./gradlew \
            clean \
            build \
            --stacktrace \
            --info \
            --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v6
        with:
          name: guiapi-advancement-${{ github.sha }}
          path: build/libs/*.jar
          if-no-files-found: error

  release:
    needs: build

    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download built artifact
        uses: actions/download-artifact@v6
        with:
          name: guiapi-advancement-${{ github.sha }}
          path: release-jars

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-jars/*.jar
          generate_release_notes: true
